#
# Copyright 2025 Oxide Computer Company
#

[project.illumos]
github = "oxidecomputer/illumos-gate"
rev = "stlouis"
unless_env = "BUILD_OS"

[project.omnios-build]
github = "oxidecomputer/helios-omnios-build"
rev = "helios3"
unless_env = "BUILD_OS"
use_ssh = false
site_sh = true

[project.omnios-extra]
github = "oxidecomputer/helios-omnios-extra"
rev = "helios3"
unless_env = "BUILD_OS"
use_ssh = false
site_sh = true

[project.pinprick]
github = "oxidecomputer/pinprick"
rev = "beab67cab00dfe70a89eb3ab9a00ce9836c62d47"
use_ssh = false
cargo_build = true

[project.phbl]
github = "oxidecomputer/phbl"
rev = "3a4905b2a6fc560cb2cd9f58c84ee057fafe437c"
use_ssh = false
cargo_toolchain = true
auto_update = true

[project.image-builder]
github = "illumos/image-builder"
rev = "5b83ae76077e9290b3355ece6c3a9476545d8a9b"
use_ssh = false
cargo_build = true
use_debug = true
auto_update = true

[project.bootserver]
github = "oxidecomputer/boot-image-tools"
rev = "ee31a3f43bcb2d02de3e4b017d4d51f3beb99858"
use_ssh = false
cargo_build = true
auto_update = true

[project.amd-host-image-builder]
github = "oxidecomputer/amd-host-image-builder"
rev = "dd68404aa16ccdd1e7b7667eca79d6c39681548a"
use_ssh = false
cargo_build = true
use_debug = true
auto_update = true

[[project.amd-host-image-builder.fixup]]
#
# We used to pin this commit.  To avoid a manual flag day, switch a user with
# this specific commit checked out as a detached HEAD back to main:
#
from_commit = "4eae23e8a86a6b5ae16e26283e9c0bee87cc2167"
to_branch = "main"

#
# -----------------------------------------------------------------------------
# NOTE: Repositories below this comment are all still private.
#
# If you do not have access to private repositories in the "oxidecomputer"
# GitHub organisation, set "OXIDE_STAFF=no" in your environment to skip
# cloning them.
# -----------------------------------------------------------------------------
# 
# BEFORE you add a private repository here, you MUST add it to the
# `access_repos` list of:
# https://github.com/oxidecomputer/omicron/blob/main/.github/buildomat/jobs/tuf-repo.sh
#
# Don't break CI!
#

[project.amd-firmware]
github = "oxidecomputer/amd-firmware"
rev = "509e931944e9373f09c91250678dcb8c5a1d84fb"
use_ssh = true
auto_update = true
unless_env = "OXIDE_STAFF"

[project.chelsio-t6-roms]
github = "oxidecomputer/chelsio-t6-roms"
rev = "fcdf32d1489412a146fa3ea3c09a176720b2cc43"
use_ssh = true
cargo_build = false
auto_update = true
unless_env = "OXIDE_STAFF"

[project.pilot]
github = "oxidecomputer/pilot"
rev = "016eceb834318bad709be07031d06b3f00d5ef51"
use_ssh = true
cargo_build = true
auto_update = true
unless_env = "OXIDE_STAFF"

[project.dmar-report]
github = "oxidecomputer/dmar-report"
rev = "a2fdbc6b34ca5b19d25304d1697437a148469c85"
use_ssh = true
cargo_build = true
auto_update = true
unless_env = "OXIDE_STAFF"
